set(CMAKE_SYSTEM_NAME Generic)

set(CMAKE_C_COMPILER x86_64-elf-gcc)
set(CMAKE_CXX_COMPILER x86_64-elf-g++)

set(CMAKE_ASM_NASM_OBJECT_FORMAT elf64)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
